name: Test Self-Hosted Runner

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Check out the code
        uses: actions/checkout@v3
      - name: Print Runner Info
        run: echo "Running on self-hosted runner!"
      - name: List DAGs
        run: ls ~/airflow/dags