name: Deploy DAGS to GCS

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:

            - name: Checkout code
              uses: actions/checkout@v3

            - id: 'auth'
              uses: 'google-github-actions/auth@v2'
              with:
                credentials_json: '${{ secrets.GCP_COMPOSE_KEY }}'

            - name: Set up Google Cloud SDK
              uses: google-github-actions/setup-gcloud@v1
              with:
                project_id: utility-replica-441110-u8

            - name: Verify authentication
              run: |
                gcloud auth list
                gcloud config list

            - name: Validate secret retrieval
              run: echo "Service account key retrieved successfully"
              env: 
                GCP_KEY: ${{ secrets.GCP_COMPOSE_KEY }}

            - name: Upload DAGs to GCS
              run: |
                gsutil cp dags/*.py gs://us-central1-cloud-composer--7381a4b6-bucket/dags/