name: Deploy DAGS to GCS

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Google Cloud SDK
              uses: google-github-actions/setup-gcloud@v1
              with:
                project_id: utility-replica-441110-u8
                service_account_key: ${{ secrets.GCP_COMPOSER_SERVICE_ACCOUNT_KEY }}

            - name: Upload DAGs to GCS
              run: |
                gsutil cp dags/*.py gs://us-central1-proj2-wb-aq-api-e203607e-bucket/dags/